### ISSUE TITLE
IOS 9.3.3 support please...

### ISSUE THREAD

**Issue by sambirempo** [cbsghost/ZeTime-Goodies#2]
I managed to install the tweak amd it work inapp but after loading the watchface I get a black screen on my watch please fix this.. I cannot upgrade to ios 10 since it is not being signed anymore

**Comment by cbsghost** [comment]
Sorry to hear that. It is not iOS 9's fault. The tweak should support from iOS 8.0 to iOS 10.2. I'm willing to solve the problem but haven't received my watch yet.  :(

**Comment by cbsghost** [comment]
Got my ZeTime and fix the bug! An update is pending to Cydia. Enjoy!!
